VALID_EXT = ['jpg', 'jpeg', 'png']

COLORMAP_AUTUMN = {'name': 'COLORMAP_AUTUMN', 'value': 0}
COLORMAP_BONE = {'name': 'COLORMAP_BONE', 'value': 1}
COLORMAP_CIVIDIS = {'name': 'COLORMAP_CIVIDIS', 'value': 17}
COLORMAP_COOL = {'name': 'COLORMAP_COOL', 'value': 8}
COLORMAP_HOT = {'name': 'COLORMAP_HOT', 'value': 11}
COLORMAP_HSV = {'name': 'COLORMAP_HSV', 'value': 9}
COLORMAP_INFERNO = {'name': 'COLORMAP_INFERNO', 'value': 14}
COLORMAP_JET = {'name': 'COLORMAP_JET', 'value': 2}
COLORMAP_MAGMA = {'name': 'COLORMAP_MAGMA', 'value': 13}
COLORMAP_OCEAN = {'name': 'COLORMAP_OCEAN', 'value': 5}
COLORMAP_PARULA = {'name': 'COLORMAP_PARULA', 'value': 12}
COLORMAP_PINK = {'name': 'COLORMAP_PINK', 'value': 10}
COLORMAP_PLASMA = {'name': 'COLORMAP_PLASMA', 'value': 15}
COLORMAP_RAINBOW = {'name': 'COLORMAP_RAINBOW', 'value': 4}
COLORMAP_SPRING = {'name': 'COLORMAP_SPRING', 'value': 7}
COLORMAP_SUMMER = {'name': 'COLORMAP_SUMMER', 'value': 6}
COLORMAP_TWILIGHT = {'name': 'COLORMAP_TWILIGHT', 'value': 18}

COLOR_MAP_TYPES = [
    COLORMAP_AUTUMN,
    COLORMAP_BONE,
    COLORMAP_CIVIDIS,
    COLORMAP_COOL,
    COLORMAP_HOT,
    COLORMAP_HSV,
    COLORMAP_INFERNO,
    COLORMAP_JET,
    COLORMAP_MAGMA,
    COLORMAP_OCEAN,
    COLORMAP_PARULA,
    COLORMAP_PINK,
    COLORMAP_PLASMA,
    COLORMAP_RAINBOW,
    COLORMAP_SPRING,
    COLORMAP_SUMMER,
    COLORMAP_TWILIGHT
]

FIRST_DELAY = 'first_delay'
LAST_DELAY = 'last_delay'
FRAME_DELAY = 'frame_delay'
LOOP = 'loop'

VIDEO_CONFIGS = {
    'full': {FIRST_DELAY: 0, LAST_DELAY: 930, FRAME_DELAY: 4, LOOP: 0},
    'default': {FIRST_DELAY: 930, LAST_DELAY: 930, FRAME_DELAY: 4, LOOP: 0},
    'test': {FIRST_DELAY: 20, LAST_DELAY: 20, FRAME_DELAY: 1, LOOP: 0}
}